name: NRDPLS
title: NRDPLS
description: Passion for life, and other nerdy things
url: "http://nrdpls.com"
icon: "http://nrdpls.com/images/SquareNRD.png"

fb_appid: 956209357778602
paginate: 10
permalink: /blog/:title/
markdown: rdiscount
excerpt_separator: <!--more-->
twitter_username: nrdpls

pygments: true

defaults: 
-
  scope:
    path: ""
    type: "posts"
  values:
      layout: "post"
