name: NRDPLS
description: Nerd + Nerd = Passion for life, and nerdy things

url: "http://nrdpls.com"

paginate: 10

markdown: rdiscount
permalink: pretty
pygments: true

default: 
-
  scope:
    path: ""
    type: "posts"
  values:
      layout: "post"
