name: NRDPLS
title: NRDPLS
description: Passion for life, and other nerdy things
url: "http://nrdpls.com"

paginate: 10
permalink: /blog/:title
markdown: rdiscount
excerpt_separator: <!--more-->
twitter_username: nrdpls

pygments: true

defaults: 
-
  scope:
    path: ""
    type: "posts"
  values:
      layout: "post"
