name: NRDPLS
description: Nerd + Nerd = Passion for life, and nerdy things

url: "http://nrdpls.com"

paginate: 10
markdown: rdiscount

pygments: true

defaults: 
-
  scope:
    path: ""
    type: "posts"
  values:
      layout: "post"
      permalink: /blog/:title
