name: NRDPLS
title: NRDPLS
description: Passion for life, and other nerdy things
url: "http://nrdpls.com"
icon: /images/SquareNRD.png

fb_appid: 956209357778602
permalink: /blog/:title/
markdown: rdiscount
excerpt_separator: <!--more-->

highlighter: rouge

defaults: 
-
  scope:
    path: ""
    type: "posts"
  values:
      layout: "post"
