name: MAN.DAD.GEEK
title: MAN.DAD.GEEK
description: Building better men and bigger geeks
url: "http://mandadgeek.com"
icon: /images/SquareNRD.png

fb_appid: 956209357778602
permalink: /blog/:title/
markdown: rdiscount
excerpt_separator: <!--more-->

highlighter: rouge

defaults: 
-
  scope:
    path: ""
    type: "posts"
  values:
      layout: "post"
